### ISSUE TITLE
conflict between self.crop_n in step_1() and self.image_stack in local_linear_regression() for detector.py

### ISSUE THREAD

**Issue by mingwhy** [adamspierer/FreeClimber#1]
Hi, adamspierer,
thank you so much for such an amazing tool!
The automation of fly spotting function really rocks!

While I was processing some climbing videos, I noticed some unusual behaviors when running FreeClimber with example movie: w1118_m_2_1.mov

This movie has 145 frames in total, instead of processing all of them, if I set the number of frames to be processed by FreeClimber between 0 and 90.
i.e.,
```
crop_0=0
crop_n=90
...
window=50
```
shown in **.cfg file.

FreeClimber_main.py would stop and give some error message at step_6(), the local_linear_regression() place.
the error message is like 'Error: input frame is not accounted for in current DataFrame'.

I checked the source code, and I guess it has something to do following lines of code in detector.py:
```
#line 75
self.image_stack = self.video_to_array(video_file,loglevel='panic')
#line 806
for i in range(len(self.image_stack) - self.window):   
#line 862-866
            self.clean_stack = self.crop_and_grayscale(stack,
                         y=y, y_max=y_max,
                         x=x, x_max=x_max,
                         first_frame=self.crop_0, last_frame=self.crop_n)
```
self.image_stack is set to be all frames contained in a mov file at the __init__;
detector.py step_1() crops frames and sends this subset of frames to downstream processing;
after fly detection, when it comes to local regression to estimate velocity, the sliding window still 'slide' through all frames in the mov instead of those cropped ones.

It works pretty well with all frames, but would run into some problem if crop_n < total.frame - window.size.

Bests!
Ming

**Comment by adamspierer** [comment]
Hi @mingwhy,

Thanks for letting me know about the issue. I've updated the Master branch's detector.py script to check for compatibility in the blank vs. crop frame ranges, and to make sure the window size is not too large.

Glad you like the program!
